name: CI
run-name: "CI workflow"

on:
    push:
      branches: ["*"]
    pull_request: 
      types: [opened]

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            sleep 180
        - run: echo "Hello World!"
        