name: CI
run-name: "CI workflow"

on:
    workflow_dispatch:
      inputs:
        stage:
          description: "Environment"
          type: "string"
          required: true
        version:
          description: "version"
          required: true

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            sleep 180
        - run: echo "Hello World!"
        