name: CI
run-name: "CI workflow"

on:
    workflow_dispatch:
      inputs:
        stage:
          description: "Environment"
          type: "string"
          required: true
        version:
          description: "version"
          required: true

jobs:
    context:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Print inputs in JSON 
          run: echo "${{ toJSON(github.event.inputs) }}"
        - name: Try setting up env
          shell: bash
          run: |
            echo "${{ toJSON(github.event.inputs) }}" | jq -r '.'
            # echo "${{ toJSON(github.event.inputs) }}" | jq -r 'to_entries | map("\(.key)=\(.value|tostring)")| .[]' | while IFS='=' read key value; do
            #   echo "${key^^}='$value'" >> $GITHUB_ENV
            # done
        - name : "Run Script"
          run: ./script.sh
        