name: CI
run-name: "CI workflow"

on:
    push:
        branches:
        - main

jobs:
    context:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: "Setup a User"
          run : echo "name=Raj" >> $GITHUB_ENV
        - name : "Run Script"
          run: ./script.sh
        