name: Demo
run-name: "Demo workflow"

on:
    workflow_dispatch:
      inputs:
        stage:
          description: "Environment"
          type: "string"
          required: true
        version:
          description: "version"
          required: true

jobs:
    context:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: rajhawaldar/inputPrint@v1
          with:
            workflowInput: "${{ inputs }}"
        
