name: Lint
run-name: "Lint workflow"

on:
    push:
      branches: ["*"]
    pull_request: 
      types: [opened]

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            sleep 120
        - run: echo "Hello World!"
        